import { CommonModule } from '@angular/common';
import { Component, OnDestroy, OnInit, inject, signal } from '@angular/core';
import { RouterLink } from '@angular/router';
import { Html5Qrcode } from 'html5-qrcode';
import { RegistrationApiService } from '../../core/services/registration-api.service';
import { AttendanceStatus } from '../../core/models/attendance.model';

type ScreenState = 'starting' | 'scanning' | 'verifying' | 'result' | 'camera-error';
type ResultStatus = AttendanceStatus | 'invalid-qr';
type ResultTone = 'success' | 'info' | 'error';

const SCANNER_ELEMENT_ID = 'attendance-qr-reader';

// Registration Ids are UUIDs generated by Utilities.getUuid() in Apps Script
// (see Code.gs createRegistration) - the exact same value encoded into the
// QR code on the registration success page. Anything else scanned is treated
// as an invalid QR code and is never sent to the backend.
const UUID_PATTERN = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i;

/**
 * /attendance-scanner - lets staff scan a participant's QR code (which
 * contains only their Registeration "Id") to check them in. All validation
 * and the AttendanceList insert happen server-side (recordAttendance in
 * Code.gs); this component only reads the camera, extracts the scanned
 * text, and displays whatever the backend decides.
 */
@Component({
  selector: 'app-attendance-scanner',
  standalone: true,
  imports: [CommonModule, RouterLink],
  templateUrl: './attendance-scanner.component.html',
  styleUrl: './attendance-scanner.component.scss'
})
export class AttendanceScannerComponent implements OnInit, OnDestroy {
  private readonly api = inject(RegistrationApiService);

  readonly scannerElementId = SCANNER_ELEMENT_ID;
  readonly screenState = signal<ScreenState>('starting');
  readonly cameraErrorMessage = signal<string | null>(null);
  readonly resultStatus = signal<ResultStatus | null>(null);
  readonly resultMessage = signal<string | null>(null);
  readonly resultId = signal<string | null>(null);

  private scanner: Html5Qrcode | null = null;
  private isCameraRunning = false;

  ngOnInit(): void {
    this.startScanning();
  }

  ngOnDestroy(): void {
    this.stopCamera();
  }

  private async startScanning(): Promise<void> {
    this.screenState.set('starting');
    this.cameraErrorMessage.set(null);
    try {
      this.scanner = new Html5Qrcode(this.scannerElementId);
      await this.scanner.start(
        { facingMode: 'environment' },
        { fps: 10, qrbox: { width: 250, height: 250 } },
        (decodedText) => this.onScanSuccess(decodedText),
        () => {
          /* Fired continuously while no QR code is in frame - expected noise, ignore. */
        }
      );
      this.isCameraRunning = true;
      this.screenState.set('scanning');
    } catch (err) {
      this.isCameraRunning = false;
      this.screenState.set('camera-error');
      this.cameraErrorMessage.set(this.mapCameraError(err));
    }
  }

  private mapCameraError(err: unknown): string {
    const name = (err as { name?: string } | undefined)?.name ?? '';
    const text = String(err);
    if (name === 'NotAllowedError' || /permission/i.test(text)) {
      return 'يرجى السماح باستخدام الكاميرا لمسح رمز QR';
    }
    if (name === 'NotFoundError' || name === 'OverconstrainedError') {
      return 'لم يتم العثور على كاميرا مدعومة على هذا الجهاز';
    }
    return 'تعذر تشغيل الكاميرا، يرجى المحاولة مرة أخرى';
  }

  private onScanSuccess(decodedText: string): void {
    if (this.screenState() !== 'scanning') {
      return; // Already processing a previous scan - ignore any extra frame callbacks.
    }
    this.pauseCamera();

    const id = decodedText.trim();
    if (!UUID_PATTERN.test(id)) {
      this.showResult('invalid-qr', 'رمز QR غير صالح', null);
      return;
    }

    this.screenState.set('verifying');
    this.api.recordAttendance(id).subscribe({
      next: (response) => this.showResult(response.status, response.message, response.data?.id ?? id),
      error: () => this.showResult('server-busy', 'تعذر الاتصال بالخادم، يرجى المحاولة مرة أخرى', id)
    });
  }

  private showResult(status: ResultStatus, message: string, id: string | null): void {
    this.resultStatus.set(status);
    this.resultMessage.set(message);
    this.resultId.set(id);
    this.screenState.set('result');
  }

  get resultTone(): ResultTone {
    const status = this.resultStatus();
    if (status === 'attendance-recorded') {
      return 'success';
    }
    if (status === 'already-recorded') {
      return 'info';
    }
    return 'error';
  }

  get resultIcon(): string {
    return this.resultTone === 'success' ? '✓' : this.resultTone === 'info' ? 'ℹ' : '✕';
  }

  /** "مسح QR آخر" - clears the result and resumes scanning. */
  scanAnother(): void {
    this.resultStatus.set(null);
    this.resultMessage.set(null);
    this.resultId.set(null);
    this.resumeCamera();
  }

  retryCamera(): void {
    void this.startScanning();
  }

  private pauseCamera(): void {
    if (this.scanner && this.isCameraRunning) {
      try {
        this.scanner.pause(true);
      } catch {
        // Ignore - camera may already be paused/stopped.
      }
    }
  }

  private resumeCamera(): void {
    if (this.scanner && this.isCameraRunning) {
      try {
        this.scanner.resume();
        this.screenState.set('scanning');
        return;
      } catch {
        // Fall through to a full restart below.
      }
    }
    void this.startScanning();
  }

  private stopCamera(): void {
    if (this.scanner && this.isCameraRunning) {
      this.scanner
        .stop()
        .then(() => this.scanner?.clear())
        .catch(() => {
          // Ignore - the component is being torn down regardless.
        });
      this.isCameraRunning = false;
    }
  }
}
